# Generated by Django 4.0.4 on 2022-08-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rend',
            name='title',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('soins dentaire urgents', 'Soins dentaire urgents')], max_length=50, null=True),
        ),
    ]
