# Generated by Django 4.0.4 on 2022-08-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0002_rend_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='rend',
            name='choice',
            field=models.CharField(default='non', max_length=100),
        ),
    ]
