# Generated by Django 4.0.4 on 2022-09-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0005_rename_title_rend_raison_rename_email_rend_courriel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rend',
            name='username',
        ),
        migrations.AlterField(
            model_name='rend',
            name='téléphone',
            field=models.IntegerField(max_length=20),
        ),
    ]
