# Generated by Django 4.0.4 on 2022-09-04 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0007_remove_rend_la_date_remove_rend_le_temps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rend',
            name='La_Date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='rend',
            name='Le_temps',
            field=models.TimeField(default=datetime.time(16, 0)),
        ),
        migrations.AddField(
            model_name='rend',
            name='Raison',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('soins dentaire urgents', 'Soins dentaire urgents')], max_length=50, null=True),
        ),
    ]
