# Generated by Django 4.0.4 on 2022-09-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0008_rend_la_date_rend_le_temps_rend_raison'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rend',
            name='Le_temps',
        ),
        migrations.AlterField(
            model_name='rend',
            name='téléphone',
            field=models.IntegerField(),
        ),
    ]
