# Generated by Django 4.0.4 on 2022-09-04 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0009_remove_rend_le_temps_alter_rend_téléphone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rend',
            name='La_Date',
        ),
        migrations.RemoveField(
            model_name='rend',
            name='Raison',
        ),
        migrations.RemoveField(
            model_name='rend',
            name='téléphone',
        ),
    ]
