# Generated by Django 4.0.4 on 2022-09-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0010_remove_rend_la_date_remove_rend_raison_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rend',
            name='téléphone',
            field=models.IntegerField(null=True),
        ),
    ]
