# Generated by Django 4.0.4 on 2023-01-09 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='services_offerts',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
