# Generated by Django 4.0.4 on 2022-07-19 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_post_category_delete_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='votre_commentaire',
        ),
    ]
