# Generated by Django 4.0.4 on 2022-07-19 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_comment_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='votre_commentaire',
            new_name='votre_nom',
        ),
    ]
